# Generated by Django 4.1.5 on 2023-03-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='client',
            name='interested_in',
            field=models.ManyToManyField(blank=True, null=True, to='myapp1.type'),
        ),
    ]
