# Generated by Django 4.1.5 on 2023-02-01 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_description_alter_client_phone_alter_orderitem_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2023, 2, 1, 17, 20, 53, 628999)),
        ),
    ]
