# Generated by Django 4.1.5 on 2023-02-03 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_description_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name=datetime.datetime(2023, 2, 3, 14, 23, 9, 541716)),
        ),
    ]
